### ISSUE TITLE
Adress already in use error

### ISSUE THREAD

**Issue by DomagojHack** [mitmproxy/pdoc#219]
#### Problem Description
I just installed pdoc  using `pip install pdoc`.  Running `pdoc ./main.py` gives the following error:

```
Traceback (most recent call last):
  File "/home/domagoj/conda/bin/pdoc", line 8, in <module>
    sys.exit(cli())
  File "/home/domagoj/conda/lib/python3.8/site-packages/pdoc/__main__.py", line 166, in cli
    with pdoc.web.DocServer(
  File "/home/domagoj/conda/lib/python3.8/site-packages/pdoc/web.py", line 104, in __init__
    super().__init__(addr, DocHandler)
  File "/home/domagoj/conda/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/domagoj/conda/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/domagoj/conda/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```
I asume I have a service on my system that is in conflict with pdoc. How can I address this issue?

#### Steps to reproduce the behavior:
1.  Installed pdoc using `pip install pdoc`
2.  Tried to run `pdoc ./main.py` in my project folder

#### System Information
Python 3.8.3 installed using conda

`pdoc --version `output:
```
pdoc: 6.1.0
Python: 3.8.3
Platform: Linux-5.8.0-7642-generic-x86_64-with-glibc2.10
```

**Comment by mhils** [comment]
pdoc by default listens on port 8080. You can use `-p 8081` or `--port 8081` to change the port in use. If you run `pdoc --help`, you'll get N overview of all available command line flags. :)

**Comment by DomagojHack** [comment]
Thanks for the tip. Setting the port using `-p` worked.
