### ISSUE TITLE
SyntaxError in templates: unexpected EOF while parsing

### ISSUE THREAD

**Issue by jstriebel** [mitmproxy/pdoc#248]
#### Problem Description
When parsing our Python 3.8 compatible code-base, the following error occurs, after generating parts of the documenation:
```
 File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 196, in macro
    {% block style_content %}
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/usr/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc.py", line 767, in decorators
    for t in doc_ast.parse(obj).decorator_list:
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc_ast.py", line 60, in parse
    return _parse_function(src)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc_ast.py", line 196, in _parse_function
    tree = ast.parse(_dedent(source))
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 9
    )
SyntaxError: unexpected EOF while parsing
```

Before, a number of user-warnings were logged, e.g. when using stringified annotations which were only imported with `typing.TYPE_CHECKING`, e.g.
```
if TYPE_CHECKING:
    from pkg import MyType

class SomeClass:
    attribute: "MyType"
```
would result in
```
UserWarning: Error parsing type annotation for pkg.some_class. Import of MyType failed: name 'MyType' is not defined
```

However, those warnings don't seem to cause the error, since some of their documentations were created successfully, before the error occurred.

Since the error is quite inexpressive, I can't give a small reproducible example. How could I generate more useful insights?

#### System Information
pdoc version 6.4.3

**Comment by jstriebel** [comment]
Hi! Thanks for adding the detailed error logging. Now I get the RuntimeWarning first instead of the original error (something seems to be off with the parser, this is related to a multiline decorator), some more UserWarnings (omitted), and finally another error `TypeError: unhashable type: 'instancemethod'`:

```
/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc_ast.py:216: RuntimeWarning: Error parsing source code: unexpected EOF while parsing (<unknown>, line 9)
===
@pytest.fixture(
    params=[
        ((10, 2), (5, 20), (2, 10)),
        ((100, 2), (-1000, 1000), (51, 100)),
        ((100, 3), (0, 50), (5, 20, 63, 87, 100)),
        ((1000, 5), (-50, 100), (2, 4, 6, 10, 50, 1000)),
    ],
    ids=lambda params: f"Coordinates in range {params[1]}, shape {params[0]} ({len(params[2])} parts)",
)

===
  warnings.warn(
/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc_ast.py:216: RuntimeWarning: Error parsing source code: unexpected EOF while parsing (<unknown>, line 12)
===
@pytest.fixture(
    params=[
        (0, 100, 100),
        (0, 100, 1000),
        (-10, 10, 100),
        (-10, 10, 99),
        (0, 1, 1),
        (0, 10, 2),
        (0, 10, 3),
    ],
    ids=lambda params: f"{params[2]} random ints in [{params[0]}, {params[1]})",
)

===
… (various UserWarnings)

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/__main__.py", line 185, in <module>
    cli()
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/__main__.py", line 153, in cli
    pdoc.pdoc(
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/__init__.py", line 386, in pdoc
    write(doc.Module(m))
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/__init__.py", line 355, in write
    outfile.write_bytes(r(mod).encode())
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/__init__.py", line 367, in r
    return render.html_module(module=mod, all_modules=all_modules)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/render.py", line 70, in html_module
    return env.select_template(
  File "/usr/local/lib/python3.8/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 650, in <module>
    {%- if loop.nextitem %}.{% endif -%}
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 953, in root
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/frame.html.jinja2", line 21, in root
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 1032, in block_body
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 1201, in block_module_contents
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 489, in macro
    </style>
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 284, in macro
    
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 570, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/templates/default/module.html.jinja2", line 196, in macro
    {% block style_content %}
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/usr/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc.py", line 767, in decorators
    for t in doc_ast.parse(obj).decorator_list:
  File "/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc_ast.py", line 55, in parse
    src = get_source(obj)
TypeError: unhashable type: 'instancemethod'
```

**Comment by mhils** [comment]
Interesting, thanks!

> (something seems to be off with the parser, this is related to a multiline decorator)

Yes - it looks like [`inspect.getsource`](https://docs.python.org/3/library/inspect.html#inspect.getsource) isn't handling nested parentheses in decorators. There's not much we can do for pdoc I think, this really should be fixed upstream.

The final crash is more homemade and needs a bit more investigation:

1. Which Python version are you on?
2. Can you upgrade to 3d48144 and run pdoc again? You should be getting a "Cannot parse ..." error, where ... points to the offending code. It would be super useful if you could either share that here or privately.

Thanks! 😃

**Comment by jstriebel** [comment]
> There already is a ticket in the Python issue tracker: https://bugs.python.org/issue38854.

Great, also just found this. Great that this is caught gracefully with your changes! :+1: 

> Which Python version are you on?

I was using Python 3.8.0 first, and just upgraded to 3.8.5, yielding the same errors and warnings.

> Can you upgrade to 3d48144 and run pdoc again? You should be getting a "Cannot parse ..." error, where ... points to the offending code.

Yes, before the same error as above, the following warning is logged:
```
/home/anyone/.local/lib/python3.8/site-packages/pdoc/doc.py:771: RuntimeWarning: Cannot parse ….cpp_functions.UnionFind.__init__: unhashable type: 'instancemethod'
```

`cpp_functions` is a module with cpp-bindings using pybind11. During the docs generation the built cpp_functions.cpython-38-x86_64-linux-gnu.so is loaded. I guess it's fair that pdoc is not able to parse this, however it would be great if those could simply be skipped with a warning (or even blacklisted manually), instead of causing an error. If you still want to investigate the specific error, I can share a rough sketch of the related `UnionFind.h`:
```
#pragma once
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
namespace py = pybind11;
using namespace py::literals;

template<typename T=uint64_t>
class UnionFind {

public:
    UnionFind(T max_element) : max_element(max_element), rank(max_element, 0){
        …
    }
    …
};

…
```

Thanks a lot for your helpful and quick responses!

**Comment by mhils** [comment]
Awesome, thanks! I've just pushed f4535da, which should fix this properly. Are you running into any other errors, or can you successfully compile now? 😃

**Comment by jstriebel** [comment]
Great, thanks a lot for your help! The docs compile now completely, just with the mentioned warnings :tada:

After testing quite a number of tools, I find that pdoc yields the best results out of the box and is most simple to use :+1: Very happy to be a new user!

PS: I'll add a PR for some styling improvements later, and just opened #249.

**Comment by mhils** [comment]
Excellent! I've just pushed 6.4.4 out, which includes these fixes. 😃
