### ISSUE TITLE
Importing azure.storage.blob Causes Error

### ISSUE THREAD

**Issue by Casey-Kiewit** [mitmproxy/pdoc#270]
#### Problem Description
Pdoc returns an error and fails to run on codebase which imports 'azure.storage.blob'.

#### Steps to reproduce the behavior:
1. Install azure
`pip install azure`
2. Create a Python file importing 'azure.storage.blob'
3. Run pdoc on this file.

#### System Information
pdoc: 7.0.3
Python: 3.7.6
Platform: Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
Could you post the error message please? I can't reproduce this locally:

```bash
λ cat foo.py
import azure.storage.blob
λ pdoc -o .render ./foo.py
# no errors
λ pdoc --version
pdoc: 7.0.3 (+4, commit 3baa26c)
Python: 3.9.4
Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
```

**Comment by Casey-Kiewit** [comment]
I get the following error message from the HTML live-view:

`Traceback (most recent call last):
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\extract.py", line 219, in load_module
    return importlib.import_module(module)
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\test.py", line 1, in <module>
    import azure.storage.blob
  File "c:\users\casey\projects\venv\lib\site-packages\azure\storage\blob\__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "c:\users\casey\projects\venv\lib\site-packages\azure\storage\blob\_blob_client.py", line 20, in <module>
    from azure.core.tracing.decorator import distributed_trace
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\__init__.py", line 30, in <module>
    from ._pipeline_client import PipelineClient
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\_pipeline_client.py", line 33, in <module>
    from .pipeline import Pipeline
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\__init__.py", line 178, in <module>
    from ._base import Pipeline  # pylint: disable=wrong-import-position
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\_base.py", line 35, in <module>
    from azure.core.pipeline.policies import HTTPPolicy, SansIOHTTPPolicy
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\policies\__init__.py", line 68, in <module>
    from ._authentication_async import AsyncBearerTokenCredentialPolicy
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\policies\_authentication_async.py", line 6, in <module>
    import asyncio
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\__init__.py", line 39, in <module>
    from .windows_events import *
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py", line 19, in <module>
    from . import windows_utils
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_utils.py", line 126, in <module>
    class Popen(subprocess.Popen):
TypeError: the first argument must be callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\web.py", line 73, in handle_request
    mod = doc.Module(extract.load_module(module))
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\extract.py", line 221, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing test`

I've been able to recreate this error on multiple computers and on multiple projects.

**Comment by mhils** [comment]
Excellent, thanks - this appears on Windows only, I can reproduce it now and will take a look. :)

**Comment by Casey-Kiewit** [comment]
Thank you so much!

**Comment by mhils** [comment]
I've just pushed a commit that fixes it locally on my system. Could you
```
pip install https://github.com/mitmproxy/pdoc/archive/main.zip
```
and confirm if it works for you as well now? 😃

**Comment by Casey-Kiewit** [comment]
That new build seems to fix that particular error, but I'm still running into errors with our main project caused by another Azure issue.

#### I was able to reproduce the error by doing the following:
`(venv) PS C:\Users\casey\Projects> cat .\test.py
import azure.core.credentials
(venv) PS C:\Users\casey\Projects> pdoc -o .render .\test.py
c:\users\casey\projects\venv\lib\site-packages\pdoc\__init__.py:406: RuntimeWarning: Error importing test:
Traceback (most recent call last):
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\extract.py", line 219, in load_module
    return importlib.import_module(module)
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\test.py", line 1, in <module>
    import azure.core.credentials
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\__init__.py", line 30, in <module>
    from ._pipeline_client import PipelineClient
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\_pipeline_client.py", line 33, in <module>
    from .pipeline import Pipeline
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\__init__.py", line 178, in <module>
    from ._base import Pipeline  # pylint: disable=wrong-import-position
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\_base.py", line 35, in <module>
    from azure.core.pipeline.policies import HTTPPolicy, SansIOHTTPPolicy
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\policies\__init__.py", line 68, in <module>
    from ._authentication_async import AsyncBearerTokenCredentialPolicy
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\policies\_authentication_async.py", line 6, in <module>
    import asyncio
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\__init__.py", line 39, in <module>
    from .windows_events import *
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py", line 19, in <module>
    from . import windows_utils
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_utils.py", line 126, in <module>
TypeError: the first argument must be callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\__init__.py", line 403, in pdoc
    m = extract.load_module(mod)
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\extract.py", line 221, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing test

  f"Error importing {mod}:\n{traceback.format_exc()}", RuntimeWarning
Traceback (most recent call last):
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\casey\Projects\venv\Scripts\pdoc.exe\__main__.py", line 7, in <module>
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\__main__.py", line 156, in cli
    format="html",  # opts.format or
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\__init__.py", line 420, in pdoc
    (output_directory / "index.html").write_bytes(index.encode())
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1225, in write_bytes
    with self.open(mode='wb') as f:
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1203, in open
    opener=self._opener)
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '.render\\index.html'`

**Comment by mhils** [comment]
This looks like the same error (`class Popen(subprocess.Popen): - TypeError: the first argument must be callable`). Could you please double-check that you are using pdoc from the main branch and not the current 7.0.3 release?
