### ISSUE TITLE
Importing azure.core.credentials on Windows Causes Import Error

### ISSUE THREAD

**Issue by Casey-Kiewit** [mitmproxy/pdoc#271]
That new build seems to fix the particular error referenced in [issue 270](https://github.com/mitmproxy/pdoc/issues/270), but I'm still running into errors with our main project caused by another Azure import issue.

#### I was able to reproduce the error by doing the following:
`(venv) PS C:\Users\casey\Projects> cat .\test.py

import azure.core.credentials

(venv) PS C:\Users\casey\Projects> pdoc -o .render .\test.py

c:\users\casey\projects\venv\lib\site-packages\pdoc\__init__.py:406: RuntimeWarning: Error importing test:
Traceback (most recent call last):
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\extract.py", line 219, in load_module
    return importlib.import_module(module)
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\test.py", line 1, in <module>
    import azure.core.credentials
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\__init__.py", line 30, in <module>
    from ._pipeline_client import PipelineClient
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\_pipeline_client.py", line 33, in <module>
    from .pipeline import Pipeline
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\__init__.py", line 178, in <module>
    from ._base import Pipeline  # pylint: disable=wrong-import-position
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\_base.py", line 35, in <module>
    from azure.core.pipeline.policies import HTTPPolicy, SansIOHTTPPolicy
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\policies\__init__.py", line 68, in <module>
    from ._authentication_async import AsyncBearerTokenCredentialPolicy
  File "c:\users\casey\projects\venv\lib\site-packages\azure\core\pipeline\policies\_authentication_async.py", line 6, in <module>
    import asyncio
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\__init__.py", line 39, in <module>
    from .windows_events import *
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py", line 19, in <module>
    from . import windows_utils
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_utils.py", line 126, in <module>
    class Popen(subprocess.Popen):
TypeError: the first argument must be callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\__init__.py", line 403, in pdoc
    m = extract.load_module(mod)
  File "C:\Users\casey\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "c:\users\casey\projects\venv\lib\site-packages\pdoc\extract.py", line 221, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing test

  f"Error importing {mod}:\n{traceback.format_exc()}", RuntimeWarning`

_Originally posted by @Casey-Kiewit in https://github.com/mitmproxy/pdoc/issues/270#issuecomment-853380439_

**Comment by mhils** [comment]
See my follow-up at https://github.com/mitmproxy/pdoc/issues/270#issuecomment-853386062 - I can't reproduce this on my machine with pdoc from the main branch. I get the same error with pdoc 7.0.3.

**Comment by Casey-Kiewit** [comment]
My apologies. It seems I didn't correctly install that new version. This command just seems to grab version 7.0.3.
`pip install https://github.com/mitmproxy/pdoc/archive/main.zip`

How would I go about installing the new build?

**Comment by mhils** [comment]
The development release reports the same version as I hadn't bumped it yet. I've just increased the version to 7.1.0, so if you re-run the command it should now show you this? :)

**Comment by Casey-Kiewit** [comment]
Pip seems to have grabbed the new version now. I think it might have been caching the old version somehow. After rerunning `pip install https://github.com/mitmproxy/pdoc/archive/main.zip` once you pushed the version change, I'm no longer getting those errors.

Thank you for your incredible work on this wonderful project! I really appreciate your help!

**Comment by mhils** [comment]
Excellent! I'll push a 7.1.0 release right out of the door then so that this works everywhere. 😃
