### ISSUE TITLE
Project install via pip install .

### ISSUE THREAD

**Issue by piyush-bajaj** [mitmproxy/pdoc#481]
#### Problem Description
When trying to install the project using the source code, using the command pip install . in the root directory of the project gives an error related to package discovery.

#### Steps to reproduce the behavior:
1.  git clone https://github.com/mitmproxy/pdoc.git pdoc #clone repo from github
2. cd pdoc 
3. virtualenv vm #create vm
4. source vm/bin/activate #activate vm
5. pip install . #install project using pip
6. get the following error:
```
 Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [79 lines of output]
      /tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      No `packages` or `py_modules` configuration, performing automatic discovery.
      `flat-layout` detected -- analysing .
      discovered packages -- ['vm', 'pdoc', 'vm.bin', 'vm.lib', 'pdoc.templates', 'pdoc.markdown2', 'pdoc.templates.deprecated', 'pdoc.templates.resources', 'pdoc.templates.default', 'pdoc.templates.deprecated.resources']
      Traceback (most recent call last):
        File "/DyPyBench/Project/project9/vm/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/DyPyBench/Project/project9/vm/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/DyPyBench/Project/project9/vm/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/DyPyBench/Project/project9/vm/lib/python3.10/site-packages/_virtualenv.py", line 21, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 867, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 140, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 195, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 242, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 286, in _expand_all_dynamic
          version=self._obtain_version(dist, package_dir),
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 332, in _obtain_version
          return _expand.version(self._obtain(dist, "version", package_dir))
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 321, in _obtain
          return self._expand_directive(
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 315, in _expand_directive
          return _expand.read_attr(directive["attr"], package_dir, root_dir)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 187, in read_attr
          _parent_path, path, module_name = _find_module(module_name, package_dir, root_dir)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 228, in _find_module
          if package_dir:
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 459, in __len__
          return len(self._target())
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 452, in _target
          self._value = self._obtain()
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 422, in _get_package_dir
          self()
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 412, in __call__
          self._dist.set_defaults(name=False)  # Skip name, we can still be parsing
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/discovery.py", line 340, in __call__
          self._analyse_package_layout(ignore_ext_modules)
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/discovery.py", line 373, in _analyse_package_layout
          or self._analyse_flat_layout()
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/discovery.py", line 430, in _analyse_flat_layout
          return self._analyse_flat_packages() or self._analyse_flat_modules()
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/discovery.py", line 436, in _analyse_flat_packages
          self._ensure_no_accidental_inclusion(top_level, "packages")
        File "/tmp/pip-build-env-jxw8zx1i/overlay/lib/python3.10/site-packages/setuptools/discovery.py", line 466, in _ensure_no_accidental_inclusion
          raise PackageDiscoveryError(cleandoc(msg))
      setuptools.errors.PackageDiscoveryError: Multiple top-level packages discovered in a flat-layout: ['vm', 'pdoc'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

```
#### System Information
OS: ubuntu 22.04
Python version: 3.10.6

**Comment by mhils** [comment]
> When trying to install the project using the source code, using the command pip install . in the root directory of the project gives an error related to package discovery.

This happens because you create a `vm` directory in pdoc's source directory, which isn't really a bug in pdoc. One simple way to work around this would be to call your virtualenv folder "venv", which would be automatically excluded by setuptools. Whatsoever, we can make package discovery explicit so that others don't have to run into this. #483 fixes it.
