### ISSUE TITLE
Can not parse dot in python file name

### ISSUE THREAD

**Issue by zhengxinchang** [mitmproxy/pdoc#491]
#### Problem Description
pdoc can not parse dot in the python file name.  The exception is shown below:

```{bash}
Warn: Cannot find spec for test.2 (from ../test.2.py):
Traceback (most recent call last):
  File "/home/zhengxc/miniconda3/lib/python3.9/site-packages/pdoc/extract.py", line 63, in walk_specs
    raise ModuleNotFoundError(modname)
ModuleNotFoundError: test.2
 (/home/zhengxc/miniconda3/lib/python3.9/site-packages/pdoc/web.py:105)
Traceback (most recent call last):
  File "/home/zhengxc/miniconda3/bin/pdoc", line 8, in <module>
    sys.exit(cli())
  File "/home/zhengxc/miniconda3/lib/python3.9/site-packages/pdoc/__main__.py", line 193, in cli
    httpd = pdoc.web.DocServer((opts.host, opts.port or 8080), opts.modules)
  File "/home/zhengxc/miniconda3/lib/python3.9/site-packages/pdoc/web.py", line 105, in __init__
    module_names = extract.walk_specs(specs)
  File "/home/zhengxc/miniconda3/lib/python3.9/site-packages/pdoc/extract.py", line 86, in walk_specs
    raise ValueError(
ValueError: No modules found matching spec: ../test.2.py
```

#### Steps to reproduce the behavior:
1.  Install the 12.3.0
2.  create a python file with name "test.2.py"
3.  run pdoc ./test.2.py

#### System Information
pdoc: 12.3.0
Python: 3.9.12
Platform: Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.31

**Comment by mhils** [comment]
Filenames with dots are generally not supported in the Python ecosystem as they are not valid module identifiers (it clashes with a file at `test/2.py`). As such, they won't be supported in pdoc. I'd recommend using an underscore instead.
