### ISSUE TITLE
Can not parse "import xxx" correctly

### ISSUE THREAD

**Issue by zhengxinchang** [mitmproxy/pdoc#492]
#### Problem Description
Basically, I have two python files and be organized like this:

```bash
├── bitcmd_build.py
├── bitcmd_utils.py
├── __init__.py
```

In the file ` bitcmd_build.py`, the `bitcmd_utils.py`  is imported like this:

```bash
import bitcmd_utils
```  
When I run the bitcmd_build.py directly, everything goes well. But if I try to build docs by using pdoc, it throws an error like this:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pdoc/extract.py", line 218, in load_module
    return importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/BITengine/bitcmd/bitcmd_build.py", line 7, in <module>
    import bitcmd_utils
ModuleNotFoundError: No module named 'bitcmd_utils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pdoc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/pdoc/__main__.py", line 185, in cli
    pdoc.pdoc(
  File "/usr/local/lib/python3.9/dist-packages/pdoc/__init__.py", line 493, in pdoc
    all_modules[module_name] = doc.Module.from_name(module_name)
  File "/usr/local/lib/python3.9/dist-packages/pdoc/doc.py", line 392, in from_name
    return cls(extract.load_module(name))
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/dist-packages/pdoc/extract.py", line 220, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing bitcmd.bitcmd_build
```  

Then I change the way of import to  `from bitcmd import bitcmd_utils`.  The pdoc works but `python bitcmd_build.py ` throws an error like this:

```bash
Traceback (most recent call last):
  File "/app/BITengine/bitcmd/bitcmd_build.py", line 7, in <module>
    from bitcmd import bitcmd_utils
ModuleNotFoundError: No module named 'bitcmd'
```

#### Steps to reproduce the behavior:
1. create three py files A.py and B.py __init.py
2.  import B.py in A .py by using "import B"
3.  run pdoc

#### System Information
pdoc: 12.3.0
Python: 3.9.5
Platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.31

**Comment by zhengxinchang** [comment]
I find an arbitrary solution:

In the bitcmd_build.py, add an addtional code:

```python
sys.path.append(".") # patch for running pdoc correctly
```

Then run pdoc:

```bash
cd /app/BITengine/bitcmd
pdoc  /app/BITengine/bitcmd  -n -d google -o /app/BITengine/documentation/bitcmd_doc --search
```

It works for both pdoc and `python bitcmd_build.py`

**Comment by zhengxinchang** [comment]
Many thanks for your fast reply. I repace  the ` import bitcmd_utils`  to `from . import bitcmd_build`, however, I still got a error when execute `python bitcmd_build.py`. 

```bash
root@BitEngine:/app/BITengine/bitcmd# python bitcmd_build.py  -d test/app1/
Traceback (most recent call last):
  File "/app/BITengine/bitcmd/bitcmd_build.py", line 11, in <module>
    from . import bitcmd_build
ImportError: attempted relative import with no known parent package
```
