### ISSUE TITLE
Store generated html docs in a folder

### ISSUE THREAD

**Issue by thierrymoudiki** [mitmproxy/pdoc#687]
#### Problem Description
Unable to **store generated html docs in a folder**. Maybe something I missed. 

#### Steps to reproduce the behavior:
1. I'm **able** to serve (display) the docs with `pdoc -t docs pkgname/*`
2. However, `pdoc -t docs pkgname/* --output-dir pkgname-docs` fails
3. Getting: 
```bash
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/bin/pdoc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/__main__.py", line 199, in cli
    pdoc.pdoc(
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/__init__.py", line 506, in pdoc
    all_modules[module_name] = doc.Module.from_name(module_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/doc.py", line 400, in from_name
    return cls(extract.load_module(name))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
```

#### System Information
pdoc --version: `14.4.0`

**Comment by mhils** [comment]
> The above exception was the direct cause of the following exception:

Please post the full output.

**Comment by thierrymoudiki** [comment]
Sure. Here it is: 

```bash
pdoc -t docs mlsauce/* --output-dir mlsauce-docs
Traceback (most recent call last):
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/extract.py", line 217, in load_module
    return importlib.import_module(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/t/Documents/Python_Packages/mlsauce/mlsauce/tests/test_adaopt.py", line 8, in <module>
    from mlsauce import mlsauce
ImportError: cannot import name 'mlsauce' from 'mlsauce' (/Users/t/Documents/Python_Packages/mlsauce/mlsauce/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/bin/pdoc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/__main__.py", line 199, in cli
    pdoc.pdoc(
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/__init__.py", line 510, in pdoc
    all_modules[module_name] = doc.Module.from_name(module_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/doc.py", line 403, in from_name
    return cls(extract.load_module(name))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/t/Documents/Python_Packages/mlsauce/venv/lib/python3.11/site-packages/pdoc/extract.py", line 219, in load_module
    raise RuntimeError(f"Error importing {module}") from e
RuntimeError: Error importing mlsauce.tests.test_adaopt
make: *** [docs] Error 1
```

**Comment by mhils** [comment]
This is not a pdoc bug. The mlsauce/tests/test_adaopt.py file tries to import mlsauce.mlsauce, which does not exist. This only manifests in the second invocation, because the web-server loads sub packages only on demand.

You need to either fix the test file, or exclude it from processing (https://pdoc.dev/docs/pdoc.html#exclude-submodules-from-being-documented).

**Comment by thierrymoudiki** [comment]
@mhils I'll try to exclude it from processing then. It's funny that by adding `--output-dir mlsauce-docs`, it starts checking the tests and fails. Great package btw Highly customizable when you know Jinja and HTML.
