### ISSUE TITLE
ImportError for local module - on el Capitan

### ISSUE THREAD

**Issue by aa403** [mitmproxy/pdoc#96]
I get the following error on OSX, 

```
Traceback (most recent call last):
  File "/usr/local/bin/pdoc", line 458, in <module>
    module = imp.load_source('__pdoc_file_module__', fp, f)
  File "/project_folder/hooks/__init__.py", line 1, in <module>
    from base import *
```

when running this command:

`pdoc hooks --all-submodules --html --overwrite --html-no-source --html-dir docs/`

my directory structure is:

```
.
├── Procfile
├── README.md
├── __init__.py
├── docs
├── hooks
│   ├── __init__.py
│   ├── active_events.py
│   ├── base.py
│   ├── loan_template.py
├── requirements.txt
└── runtime.txt
```

and hooks/**init**.py contains

```
from base import *
from loan_template import *
from active_events import *
```

I do not get this issue on my Ubuntu machine, having just installed pdoc 0.3.1 on both, via pip.

any ideas?

**Comment by sanseihappa** [comment]
Have you tried pdoc 0.3.2?  Also, your traceback is missing the actual exception... what is it?

**Comment by TorbenFricke** [comment]
I'm having the very same issue on 0.3.2. Any ideas?

**Comment by BurntSushi** [comment]
Could someone please include the full traceback and code that is provoking the problem?

**Comment by TorbenFricke** [comment]
Here is the full traceback: 

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pdoc", line 4, in <module>
    __import__('pkg_resources').run_script('pdoc==0.3.2', 'pdoc')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pdoc-0.3.2-py2.7.egg/EGG-INFO/scripts/pdoc", line 472, in <module>
    module = imp.load_source('__pdoc_file_module__', fp, f)
  File "/Users/Torben/Dropbox/Uni/Masterarbeit/Audi/IALmodules/__init__.py", line 16, in <module>
    import utils
ImportError: No module named utils
`

I was able to fix the issue by adding the following snipping to the beginning of "__init__.py":

`import sys, os
_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(_path)`

**Comment by mhils** [comment]
The module loader has been revamped, so if this problem still exists please open a new one! :)
